from __future__ import annotations
from typing import Any, Callable, Iterable, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    import pandas as pd

class BackendMainWidgetProtocol(Protocol):
    def addTable(self, table: BackendTableProtocol): ...
    def removeTable(self, index: int): ...
    def addDockWidget(self, dock): ...
    def stackIndex(self) -> int: ...
    def setStackIndex(self, index: int) -> None: ...

class BackendTableProtocol(Protocol):
    def __init__(self, data: pd.DataFrame): ...
    def refreshTable(self) -> None: ...
    def rowCount(self) -> int: ...
    def columnCount(self) -> int: ...
    
    # properties
    def editability(self) -> bool: ...
    def setEditability(self, editable: bool) -> None: ...
    def selections(self) -> list[tuple[slice, slice]] : ...
    def setSelections(self, selections: Iterable[tuple[slice, slice]]): ...
    def zoom(self) -> float: ...
    def setZoom(self, value: float): ...
    def precision(self) -> int: ...
    def setPrecision(self, ndigits: int) -> None: ...
    
    # signal connection
    def connectItemChangedSignal(self, slot: Callable[[Any], Any]): ...
    def connectSelectionChangedSignal(self, slot: Callable[[Any], Any]): ...
