from __future__ import annotations
from typing import Any, Callable, Iterable, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    import pandas as pd

class BackendMainWidgetProtocol(Protocol):
    def addTable(self, table): ...
    def removeTable(self, index): ...

class BackendTableProtocol(Protocol):
    def __init__(self, data: pd.DataFrame): ...
    def editability(self) -> bool: ...
    def setEditability(self, editable: bool) -> None: ...
    def rowCount(self) -> int: ...
    def columnCount(self) -> int: ...
    def getSelections(self) -> list[tuple[slice, slice]] : ...
    def setSelections(self, selections: Iterable[tuple[slice, slice]]): ...
    def connectItemChangedSignal(self, slot: Callable[[Any], Any]): ...
    def connectSelectionChangedSignal(self, slot: Callable[[Any], Any]): ...
